# Analysis title
analysis: p22162_Lara_Analysis
# short name to identify reference genome version, used to label outputs
reference: GRCm38
# root dir is base of mounted file system, might change by machine. Include the 
# path upto the 'runs/' folder. All subsequent paths should be relative to this root
rootDir: /Volumes/yerkes/genomelab/illumina/runs/ #/yerkes-cifs/runs/
# Reference genome directory that holds "geneInfo.tab" 
referenceDir: Genome_references/homo_sapiens/GRCh38/ensembl_107/star_index_2.7.9a/
# STAR feature counts files directory
alignmentDir: Analysis/2022_Analyses/p22162_Lara/RNA/p22162_Lara_Processing/
# Suffix used to identify read count tables output by STAR
STARreadSuffix: ReadsPerGene.out.tab
# Samples to drop, using the same names as the "sample ID" column of the exp_design_template
dropSamples:
- Emory-102.2
# - Emory-004
# - Emory-043
# - Emory-104
# Formula for DESeq2 design. Has not been rigorously tested with multifactor designs. Consider
# making your design one combined factor as per the vignette: https://bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#contrasts
# Group should always be included as the primary term. Additional terms can be included from the
# sample metadata by using the column name of the term in that table
design: '0 + Group'
# Level of primary design factor to use as baseline for comparisons in heatmap
designBaseline: adeno
# Contrasts to examine, based on levels of the factor(s) used as the design formula.
# Separate levels with "vs" or "over" and some characters (spaces, underscores, dashes etc)
# E.g.: Level1_vs_Level2   or   AB over BC
contrasts: 
- adenocarcinoma_vs_squamous
- adenocarcinoma_vs_plasmacytoid
- adencarcinomao_vs_sarcomatoid
- 'adenocarcinoma_vs_small cell'
#- plasmacytoid_vs_squamous
#- plasmacytoid_vs_sarcomatoid
#- 'plasmacytoid_vs_small cell'
#- sarcomatoid_vs_squamous
#- 'sarcomatoid_vs_small cell'
#- 'small cell_vs_squamous'
# Character in groupPairs that separates groups (e.g. Group1_vs_Group2 would have _ as the splitChar)
contrastSplitChar:
- _
# Genes of interest to highlight in volcano plots and individual plots
geneList:
## requested genes
- NECTIN4
- CD274
- TACSTD2
- EFNB2
# https://www.nature.com/articles/nature12965
- FGFR3
- miR-99a
- miR-100
- miR-125b
- miR-145
- ERBB2 #HER2
- KRT5
- KRT6A
- KRT14
- EGFR
- GATA3
- FOXA1
- UPK3A
- ESR2
- miR-220a
- miR-220b
- KRT20
- PPARG
- SNX31
- UPK1A
- UPK2
- FGFR3
- PGM5
- DES
- C7
- p53
- CD44
- KRT
- TP53
- RB1
- E2F3
- CDH1
- HER2
- MDM2
- CDKN1A
## NONCODING RNAS lncRNAs
- DANCR
- GAS5
- MALAT1
- NEAT1
- NORAD
- UCA1
- CD274
- PDCD1
# Metadata to use for PCA plot overlays. Use column names in the exp_design file. Leave blank to ignore aes
pcaMapping: 
  color: Group
  shape: 
  label: 
  path:
  ellipse: Group
# Adjusted P value cutoff
alpha: 0.05
# Order that samples appear on figures. List order of metadata factors (columns in exp_design_template) to sort by
# Would not be used if metadata table is made manually
sampleGrouping: 
- Group
- Batch
- CollectionDate
# GSEA 
gseaFilesPath: tools/fGSEA/homo_sapiens
gseaCollections:
- c2.cp.v7.5.1.symbols.gmt  
- c5.go.bp.v7.5.1.symbols.gmt
- h.all.v7.5.1.symbols.gmt
libraryType: antisense

